Repository kubernetes-sigs/kube-batch, pull requests merged in 2018-02, with the labels that each got.

#167 Added Assigned pods slice.
  pkg/batchd/cache/pod_set.go
  pkg/batchd/cache/pod_set_test.go
  pkg/batchd/cache/queue_info_test.go
  pkg/batchd/controller/policy_controller.go
  pkg/batchd/policy/drf/drf.go
  pkg/batchd/policy/drf/drf_test.go
  pkg/batchd/policy/drf/podset_info.go
Labels: cncf-cla: yes, size/M

#168 *: Add golinter
  .travis.yml
  Makefile
  hack/.golint_failures
  hack/verify-golint.sh
Labels: cncf-cla: yes, lgtm, size/L

#169 Make minor fixes to cache.go
  pkg/batchd/cache/cache.go
Labels: cncf-cla: yes, lgtm, size/XS

#171 batchd_tutorial: Fix a typo
  doc/usage/batchd_tutorial.md
Labels: cncf-cla: yes, lgtm, size/XS

#173 code refine
  pkg/batchd/policy/drf/drf.go
  pkg/batchd/policy/drf/podset_info.go
Labels: cncf-cla: yes, size/M
