Repository kubernetes-sigs/kube-batch, pull requests merged in 2018-12, with the labels that each got.

#486 add user Mogu inc to the doc
  doc/usage/who-is-using.md
Labels: cncf-cla: yes, size/XS

#488 Renamed pkg alias.
  pkg/scheduler/framework/statement.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/L

#489 Added Statement.
  pkg/scheduler/framework/statement.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#490 Add version options for kube-batch
  Makefile
  cmd/kube-batch/app/options/options.go
  cmd/kube-batch/app/server.go
  pkg/version/version.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#491 Update nodeInfo once node was cordoned
  pkg/scheduler/cache/event_handlers.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#493 fix typo: kuberentes -> kubernetes
  doc/design/queue_api.md
  doc/design/queuejob_api.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#499 Added Statement for eviction in batch.
  Makefile
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/actions/reclaim/reclaim.go
  pkg/scheduler/api/node_info.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/framework/statement.go
  pkg/scheduler/plugins/gang/gang.go
  test/e2e/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#500 Set 2 compute nodes.
  hack/run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#501 Set 2 compute nodes.
  hack/run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#503 Update OWNERS
  OWNERS
Labels: cncf-cla: yes, lgtm, size/XS

#502 Reset node number to 3.
  hack/run-e2e.sh
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/plugins/drf/drf.go
  pkg/scheduler/plugins/priority/priority.go
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#505 Added e2e test for Statement.
  pkg/scheduler/api/node_info.go
  test/e2e/job.go
  test/e2e/util.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#506 Automated cherry pick of #502: Reset node number to 3. #505: Added e2e test for Statement.
  hack/run-e2e.sh
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/api/node_info.go
  pkg/scheduler/plugins/drf/drf.go
  pkg/scheduler/plugins/priority/priority.go
  pkg/scheduler/plugins/proportion/proportion.go
  test/e2e/job.go
  test/e2e/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#510 Automated cherry pick of #509: PodGroup can not be reclaimed.
  pkg/scheduler/plugins/gang/gang.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#511 Added task priority e2e.
  test/e2e/job.go
  test/e2e/predicates.go
  test/e2e/queue.go
  test/e2e/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#513 remove the debug log to avoid flooding logs
  pkg/scheduler/scheduler.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#517 Updated version to 0.3
  deployment/kube-batch/values.yaml
  doc/usage/tutorial.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#518 Updated changlog for v0.3
  CHANGLOG.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#519 Update CHANGLOG.md
  CHANGLOG.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#523 Build release images.
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#524 Automated cherry pick of #523: Build release images.
  Makefile
Labels: approved, cncf-cla: yes, size/S
