Repository kubernetes-sigs/kube-batch, pull requests merged in 2018-10, with the labels that each got.

#383 Renamed spec.NumMember to spec.MinMember.
  config/crds/scheduling_v1alpha1_podgroup.yaml
  pkg/apis/scheduling/v1alpha1/types.go
  pkg/scheduler/api/job_info.go
  test/util.go
Labels: area/api, cncf-cla: yes, kind/api-change, size/S

#386 Updated Event source to kube-batch.
  pkg/scheduler/cache/cache.go
Labels: cncf-cla: yes, size/XS

#391 Renamed kube-batchd to kube-batch.
  Makefile
  README.md
  cmd/kube-batch/app/options/options.go
  cmd/kube-batch/app/server.go
  cmd/kube-batch/main.go
  deployment/Dockerfile
  deployment/kube-batch/Chart.yaml
  deployment/kube-batch/templates/deployment.yaml
  deployment/kube-batch/values.yaml
  doc/images/kube-batch.png
  doc/usage/tutorial.md
  example/job.yaml
  hack/.golint_failures
  hack/run-e2e.sh
  test/e2e.go
  test/util.go
Labels: approved, cncf-cla: yes, size/M

#396 Fixed build images error.
  Makefile
  deployment/images/Dockerfile
Labels: approved, cncf-cla: yes, size/XS

#397 Fix build error.
  Makefile
Labels: approved, cncf-cla: yes, size/XS

#399 Update name in images.
  doc/images/kube-batch.png
Labels: approved, cncf-cla: yes, size/XS

#408 Disabled e2e in CI.
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#404 Renamed numMember to minMember in tutorial.
  doc/usage/tutorial.md
  example/job.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#405 Moved e2e test to its own dir.
  hack/.golint_failures
  hack/run-e2e.sh
  test/e2e/e2e.go
  test/e2e/e2e_test.go
  test/e2e/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#410 Upgrade DIND version.
  .travis.yml
  hack/dind-cluster-v1.11.sh
  hack/run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#411 Automated cherry pick of #410: Upgrade DIND version.
  hack/dind-cluster-v1.11.sh
  hack/run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#407 change kar-scheduler to kube-batch
  cmd/kube-batch/app/server.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#398 Automated cherry pick of #396: Fixed build images error. #397: Fix build error.
  Makefile
  deployment/images/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#413 Added change log.
  CHANGLOG.md
Labels: approved, cncf-cla: yes, lgtm

#414 Added --schedule-period
  cmd/kube-batch/app/options/options.go
  cmd/kube-batch/app/server.go
  pkg/scheduler/scheduler.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#419 Imported golang golint.
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#421 Refactor e2e cases.
  test/e2e/e2e_test.go
  test/e2e/job.go
  test/e2e/predicates.go
  test/e2e/queue.go
  test/e2e/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#417 fix BestEffort for overused
  pkg/scheduler/plugins/priority/priority.go
  test/e2e/job.go
  test/e2e/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#423 fix err log
  pkg/scheduler/plugins/predicates/predicates.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#418 Supported Pod Affinity/Anti-Affinity Predicate.
  pkg/scheduler/plugins/predicates/predicates.go
  test/e2e/job.go
  test/e2e/predicates.go
  test/e2e/queue.go
  test/e2e/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#428 Using jobSpec for e2e.
  test/e2e/job.go
  test/e2e/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#429 Using jobSpec for more e2e.
  test/e2e/job.go
  test/e2e/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#430 Using jobSpec in predicate e2e.
  test/e2e/predicates.go
  test/e2e/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#436 Updated vendors.
  Godeps/Godeps.json
  vendor/github.com/inconshreveable/mousetrap/LICENSE
  vendor/github.com/inconshreveable/mousetrap/README.md
  vendor/github.com/inconshreveable/mousetrap/trap_others.go
  vendor/github.com/inconshreveable/mousetrap/trap_windows.go
  vendor/github.com/inconshreveable/mousetrap/trap_windows_1.4.go
  vendor/github.com/spf13/cobra/.gitignore
  vendor/github.com/spf13/cobra/.mailmap
  vendor/github.com/spf13/cobra/.travis.yml
  vendor/github.com/spf13/cobra/LICENSE.txt
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/args.go
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/bash_completions.md
  vendor/github.com/spf13/cobra/cobra.go
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/command_notwin.go
  vendor/github.com/spf13/cobra/command_win.go
  vendor/github.com/spf13/cobra/zsh_completions.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/helpers.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/types_jsonschema.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.pb.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.proto
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/marshal.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types_jsonschema.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/clientset.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/apiextensions_client.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/generated_expansion.go
  vendor/k8s.io/client-go/discovery/fake/discovery.go
  vendor/k8s.io/client-go/testing/actions.go
  vendor/k8s.io/client-go/testing/fake.go
  vendor/k8s.io/client-go/testing/fixture.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#437 Automated cherry pick of #414: Added --schedule-period
  cmd/kube-batch/app/options/options.go
  cmd/kube-batch/app/server.go
  pkg/scheduler/scheduler.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#433 Added backfill action for BestEffort pods.
  hack/.golint_failures
  pkg/scheduler/actions/backfill/backfill.go
  pkg/scheduler/factory.go
  pkg/scheduler/plugins/priority/priority.go
  pkg/scheduler/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#438 Using jobSpec for queue e2e.
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/event_handlers.go
  test/e2e/job.go
  test/e2e/predicates.go
  test/e2e/queue.go
  test/e2e/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#440 Updated node info if taints and lables changed.
  pkg/scheduler/cache/event_handlers.go
  test/e2e/predicates.go
  test/e2e/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#442 Checked allowed pod number on node.
  pkg/scheduler/api/resource_info.go
  pkg/scheduler/plugins/predicates/predicates.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#443 Checked pod group unschedulable event.
  pkg/scheduler/framework/session.go
  pkg/scheduler/plugins/gang/gang.go
  test/e2e/job.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#445 Update issue/pr templates.
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#450 Updated README.
  README.md
Labels: approved, cncf-cla: yes, lgtm

#451 Add DLaaS owners.
  contrib/DLaaS/OWNERS
Labels: approved, cncf-cla: yes, lgtm

#455 Check node spec for unschedulable as well
  pkg/scheduler/plugins/predicates/predicates.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#458 Removed node.PipelineTask.
  pkg/scheduler/api/node_info.go
  pkg/scheduler/framework/session.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/M

#460 Renamed EvictFunc to DeallocateFunc.
  .travis.yml
  hack/update-gofmt.sh
  pkg/scheduler/framework/event.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/plugins/drf/drf.go
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, cncf-cla: yes, lgtm, size/S
