Repository kubernetes-sigs/kube-batch, pull requests merged in 2018-03, with the labels that each got.

#174 gang scheduling
  pkg/batchd/cache/cache_test.go
  pkg/batchd/cache/node_info.go
  pkg/batchd/cache/node_info_test.go
  pkg/batchd/policy/drf/drf.go
  pkg/batchd/policy/drf/podset_info.go
Labels: cncf-cla: yes, size/L

#175 code refine
  pkg/batchd/cache/node_info.go
  pkg/batchd/policy/drf/drf.go
  pkg/batchd/policy/drf/podset_info.go
Labels: cncf-cla: yes, size/M

#176 add ut cases for gang scheduling
  pkg/batchd/policy/drf/drf_test.go
Labels: cncf-cla: yes, size/L

#179 doc update for gang scheduling and pod priority
  doc/usage/batchd_tutorial.md
Labels: cncf-cla: yes, kind/documentation, size/M

#177 scheduling pod by priority in same PodSet
  pkg/batchd/cache/pod_set.go
  pkg/batchd/policy/drf/podset_info.go
Labels: cncf-cla: yes, size/S

#180 Readme typo batched -> batchd
  README.md
Labels: cncf-cla: yes, size/XS

#182 <design docs> Minor fixes: MarkDown formatting, typos
  doc/design/preemption.md
  doc/design/queue_api.md
  doc/design/queuejob_api.md
Labels: cncf-cla: yes, size/M

#188 doc/usage: improve documentation of batchd and quotalloc tutorials
  doc/usage/batchd_tutorial.md
  doc/usage/quotalloc_tutorial.md
Labels: cncf-cla: yes, size/L

#184 fix version compare
  hack/lib/golang.sh
Labels: cncf-cla: yes, size/XS

#189 kube-batchd tutorial packaging and deployment fix
  doc/usage/batchd_tutorial.md
Labels: cncf-cla: yes, size/S

#193 init queuejob apis
  cmd/kube-batchd/app/server.go
  pkg/batchd/apis/v1/queuejob.go
  pkg/batchd/apis/v1/register.go
  pkg/batchd/apis/v1/zz_generated.deepcopy.go
  pkg/batchd/client/clientset/typed/v1/queuejob.go
  pkg/batchd/client/informers/factory.go
  pkg/batchd/client/informers/v1/interface.go
  pkg/batchd/client/informers/v1/queuejob.go
  pkg/batchd/client/listers/v1/queuejob.go
  pkg/batchd/client/queuejob.go
  pkg/batchd/controller/queuejob_controller.go
Labels: cncf-cla: yes, size/XL

#194 init queuejob controller
  pkg/batchd/apis/v1/queuejob.go
  pkg/batchd/controller/queuejob_controller.go
  pkg/batchd/controller/queuejob_info.go
  pkg/batchd/controller/utils.go
Labels: cncf-cla: yes, lgtm, size/L
