Repository kubernetes-sigs/kube-batch, pull requests merged in 2018-04, with the labels that each got.

#196 Simplity the loop in drf.Allocate() a little bit
  pkg/batchd/policy/drf/drf.go
Labels: cncf-cla: yes, size/XS

#199 QueueJob API update
  pkg/batchd/apis/v1/queuejob.go
  pkg/batchd/apis/v1/zz_generated.deepcopy.go
  pkg/batchd/controller/queuejob_controller.go
Labels: cncf-cla: yes, size/M

#200 enhance controller to handle queuejob lifecycle
  cmd/kube-batchd/app/server.go
  pkg/batchd/apis/v1/queuejob.go
  pkg/batchd/apis/v1/zz_generated.deepcopy.go
  pkg/batchd/client/clientset/typed/v1/client.go
  pkg/batchd/controller/queuejob/controller.go
  pkg/batchd/controller/queuejob/utils.go
  pkg/batchd/controller/queuejob_controller.go
  pkg/batchd/controller/queuejob_info.go
  pkg/batchd/controller/utils.go
Labels: cncf-cla: yes, size/XL

#201 add queuejob usage
  doc/usage/batchd_tutorial.md
Labels: cncf-cla: yes, size/M

#203 support NodeSelector for PodSet
  pkg/batchd/cache/pod_set.go
  pkg/batchd/cache/pod_set_test.go
  pkg/batchd/cache/queue_info_test.go
  pkg/batchd/controller/policy_controller.go
  pkg/batchd/controller/queuejob/controller.go
  pkg/batchd/policy/drf/drf.go
  pkg/batchd/policy/drf/drf_test.go
  pkg/batchd/policy/drf/utils.go
Labels: cncf-cla: yes, size/L
