Repository kubernetes-sigs/kube-batch, pull requests merged in 2018-11, with the labels that each got.

#463 Added links to related users.
  doc/usage/who-is-using.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#420 Fixing some grammatical and syntax issues
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#464 Order gang scheduled jobs based on time of arrival
  pkg/scheduler/api/job_info.go
  pkg/scheduler/plugins/gang/gang.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#465 Enable PDB based gang scheduling with discrete queues.
  cmd/kube-batch/app/options/options.go
  cmd/kube-batch/main.go
  pkg/scheduler/api/job_info.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#466 Ordered Job by creation time.
  pkg/scheduler/framework/session.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, sig/scheduling, size/XS

#470 Fixed event recorder schema to include definitions for non kube-batch entities
  pkg/client/clientset/versioned/scheme/register.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#471 Remove duplicated words
  contrib/DLaaS/hack/lib/golang.sh
  contrib/DLaaS/hack/lib/util.sh
  hack/lib/golang.sh
  hack/lib/util.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#472 Fix some typos
  contrib/DLaaS/pkg/controller/queuejobresources/pod/pod.go
  doc/design/queue_api.md
  doc/design/queuejob_api.md
  doc/usage/tutorial.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#477 Fix typo in tutorial.md
  doc/usage/tutorial.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#476 Delete the redundant code
  pkg/scheduler/cache/event_handlers.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#478 Fixed name issues.
  .travis.yml
  hack/run-e2e.sh
  pkg/scheduler/actions/backfill/backfill.go
  pkg/scheduler/plugins/predicates/predicates.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#480 Added Pipelined Pods as valid tasks.
  pkg/scheduler/plugins/gang/gang.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/XS

#482 Updated DIND version when cleanup
  hack/run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS
