Repository kubernetes-sigs/kube-batch, pull requests merged in 2018-07, with the labels that each got.

#257 Added error handling for Bind & Evict.
  pkg/controller/queuejob/utils.go
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/decorate/decorate.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/api/helpers.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/api/node_info.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/event_handlers.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/plugins/drf/drf.go
  pkg/scheduler/plugins/gang/gang.go
  test/util.go
Labels: cncf-cla: yes, size/L

#259 Fixed Bind & Evict error handling issue.
  pkg/scheduler/api/job_info.go
  pkg/scheduler/api/node_info.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/event_handlers.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/scheduler.go
  test/e2e.go
  test/util.go
Labels: cncf-cla: yes, size/L

#260 Init DRF share when open session.
  pkg/scheduler/cache/cache.go
  pkg/scheduler/plugins/drf/drf.go
Labels: cncf-cla: yes, size/XS

#265 Removed duplicated message.
  pkg/scheduler/scheduler.go
Labels: cncf-cla: yes, size/XS

#267 kube-arbitrator deployment files.
  Makefile
  deployment/Dockerfile
  deployment/Dockerfile.ctrl
  deployment/Dockerfile.sched
  deployment/kube-arbitrator/templates/deployment.yaml
  deployment/kube-arbitrator/values.yaml
  deployment/supervisord.conf
  doc/usage/tutorial.md
Labels: cncf-cla: yes, size/L

#269 Added multiple pod template in QueueJob.
  pkg/apis/v1alpha1/queuejob.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/queuejob/queuejob_controller.go
  pkg/controller/queuejob/utils.go
  pkg/karcli/job/list.go
  pkg/karcli/job/run.go
  test/e2e.go
  test/util.go
Labels: cncf-cla: yes, size/XL

#270 Added contrib dir for vendors.
  contrib/README.md
Labels: cncf-cla: yes, size/XS

#272 Added scheduler confmap.
  cmd/kar-scheduler/app/options/options.go
  cmd/kar-scheduler/app/server.go
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/actions/decorate/decorate_test.go
  pkg/scheduler/actions/preempt/preempt_test.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/interface.go
  pkg/scheduler/factory.go
  pkg/scheduler/framework/framework.go
  pkg/scheduler/framework/interface.go
  pkg/scheduler/framework/plugins.go
  pkg/scheduler/plugins/drf/drf.go
  pkg/scheduler/plugins/gang/gang.go
  pkg/scheduler/plugins/priority/priority.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/util.go
Labels: cncf-cla: yes, size/L

#276 Removed old args and enable logs.
  deployment/kube-arbitrator/templates/deployment.yaml
Labels: cncf-cla: yes, size/XS

#277 Removed duplicated PDB informer.
  pkg/scheduler/cache/cache.go
Labels: cncf-cla: yes, size/XS

#278 Updated EventHandler type.
  pkg/apis/v1alpha1/schedulingspec.go
  pkg/client/informers/factory.go
  pkg/client/informers/generic.go
  pkg/controller/queuejob/queuejob_controller.go
  pkg/scheduler/cache/cache.go
Labels: cncf-cla: yes, size/M

#279 Updated yaml file for multiple pod.
  doc/usage/tutorial.md
Labels: cncf-cla: yes, size/M

#281 Removed delete action in addTask.
  pkg/scheduler/cache/event_handlers.go
Labels: cncf-cla: yes, size/XS

#282 Preemption within Job.
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/framework/session.go
Labels: cncf-cla: yes, size/M

#283 Checked under request jobs.
  pkg/scheduler/actions/preempt/preempt.go
Labels: cncf-cla: yes, size/S

#284 Enhanced job deletion.
  pkg/scheduler/api/helpers.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/event_handlers.go
Labels: cncf-cla: yes, size/M

#287 Deleted Task in cache.
  pkg/scheduler/cache/event_handlers.go
  pkg/scheduler/framework/session.go
Labels: cncf-cla: yes, size/M

#289 Deleted Job when PDB deleted.
  pkg/scheduler/api/helpers.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/cache/event_handlers.go
Labels: cncf-cla: yes, size/S

#290 Error message typo.
  pkg/scheduler/cache/event_handlers.go
Labels: cncf-cla: yes, size/XS

#291 Skip finished pods when calculating used resources.
  test/util.go
Labels: cncf-cla: yes, size/XS

#292 Removed unnecessary install steps in CI.
  .travis.yml
Labels: cncf-cla: yes, size/S

#293 scheduler name can be specified as part of the QueueJob Spec
  pkg/apis/v1alpha1/queuejob.go
  pkg/controller/queuejob/utils.go
  test/e2e.go
  test/util.go
Labels: cncf-cla: yes, size/M

#297 Added comments for QueueJob
  pkg/apis/v1alpha1/queuejob.go
Labels: cncf-cla: yes, size/XS

#298 Adding coverage flag in Makefile
  Makefile
Labels: cncf-cla: yes, lgtm, size/XS

#304 kube-batchd can not aware of the changes of gpu resources when scale up cluster.
  pkg/batchd/cache/cache.go
  pkg/batchd/cache/node_info.go
Labels: cncf-cla: yes, size/S

#295 Added FfDL directory for contribute.
  contrib/FfDL/OWNERS
Labels: cncf-cla: yes, size/XS

#305 Updated nodes if allocatable changed.
  pkg/scheduler/api/node_info.go
  pkg/scheduler/cache/event_handlers.go
Labels: cncf-cla: yes, size/M

#307 Added e2e test by dind.
  .travis.yml
  Makefile
  hack/dind-cluster-v1.11.sh
  hack/e2e-cluster.sh
  test/util.go
Labels: cncf-cla: yes, size/XXL

#306 Enable LeaderElect for both scheduler and controller
  Godeps/Godeps.json
  cmd/kar-controllers/app/options/options.go
  cmd/kar-controllers/app/server.go
  cmd/kar-controllers/main.go
  cmd/kar-scheduler/app/options/options.go
  cmd/kar-scheduler/app/server.go
  cmd/kar-scheduler/main.go
  pkg/controller/queuejob/queuejob_controller.go
  vendor/github.com/golang/groupcache/LICENSE
  vendor/github.com/golang/groupcache/lru/lru.go
  vendor/k8s.io/apimachinery/pkg/util/mergepatch/OWNERS
  vendor/k8s.io/apimachinery/pkg/util/mergepatch/errors.go
  vendor/k8s.io/apimachinery/pkg/util/mergepatch/util.go
  vendor/k8s.io/apimachinery/pkg/util/strategicpatch/OWNERS
  vendor/k8s.io/apimachinery/pkg/util/strategicpatch/errors.go
  vendor/k8s.io/apimachinery/pkg/util/strategicpatch/meta.go
  vendor/k8s.io/apimachinery/pkg/util/strategicpatch/patch.go
  vendor/k8s.io/apimachinery/pkg/util/strategicpatch/types.go
  vendor/k8s.io/apimachinery/third_party/forked/golang/json/OWNERS
  vendor/k8s.io/apimachinery/third_party/forked/golang/json/fields.go
  vendor/k8s.io/client-go/tools/leaderelection/OWNERS
  vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/endpointslock.go
  vendor/k8s.io/client-go/tools/leaderelection/resourcelock/interface.go
  vendor/k8s.io/client-go/tools/record/OWNERS
  vendor/k8s.io/client-go/tools/record/doc.go
  vendor/k8s.io/client-go/tools/record/event.go
  vendor/k8s.io/client-go/tools/record/events_cache.go
  vendor/k8s.io/client-go/tools/record/fake.go
  vendor/k8s.io/kube-openapi/LICENSE
  vendor/k8s.io/kube-openapi/pkg/util/proto/doc.go
  vendor/k8s.io/kube-openapi/pkg/util/proto/document.go
  vendor/k8s.io/kube-openapi/pkg/util/proto/openapi.go
Labels: cncf-cla: yes, size/XXL

#312 Added e2e for node affinity.
  test/e2e.go
  test/util.go
Labels: cncf-cla: yes, size/L
