Repository kubernetes-sigs/kube-batch, pull requests merged in 2018-06, with the labels that each got.

#237 Updated documentation for separate controllers done in 233 and 212.
  deployment/kube-batchd.yaml
  deployment/kube-queue-ctrl.yaml
  deployment/kube-queuejob-ctrl.yaml
  doc/usage/batchd_tutorial.md
Labels: cncf-cla: yes, size/M

#243 Corrected the informer.
  pkg/client/informers/generic.go
Labels: cncf-cla: yes, lgtm, size/XS

#244 Started PDB informer.
  pkg/scheduler/cache/cache.go
Labels: cncf-cla: yes, size/XS

#250 Disabled preemption by default.
  cmd/kar-scheduler/app/options/options.go
  cmd/kar-scheduler/app/server.go
  pkg/scheduler/factory.go
  pkg/scheduler/framework/plugins.go
  pkg/scheduler/scheduler.go
Labels: cncf-cla: yes, size/M

#251 Renamed actions to action.
  cmd/kar-scheduler/app/options/options.go
Labels: cncf-cla: yes, size/XS

#255 Corrected 'node.releasing' counter error.
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/api/helpers.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/api/node_info.go
  pkg/scheduler/framework/event.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/plugins/drf/drf.go
  pkg/scheduler/plugins/gang/gang.go
  test/e2e.go
  test/util.go
Labels: cncf-cla: yes, size/M

#252 template for extended QueueJob definition to support ML workloads
  pkg/apis/v1alpha1/queuejob_ex.go
  pkg/apis/v1alpha1/register.go
  pkg/apis/v1alpha1/zz_generated.deepcopy.go
Labels: cncf-cla: yes, size/L
