Repository kubernetes-sigs/kube-batch, pull requests merged in 2018-09, with the labels that each got.

#342 Move extensions out of tree.
  Makefile
  cmd/kar-controllers/app/options/options.go
  cmd/kar-controllers/app/server.go
  cmd/kar-scheduler/main.go
  cmd/karcli/karcli.go
  cmd/kube-batchd/app/options/options.go
  cmd/kube-batchd/app/server.go
  cmd/kube-batchd/main.go
  config/crds/extensions_v1alpha1_job.yaml
  config/crds/scheduling_v1alpha1_podgroup.yaml
  config/crds/scheduling_v1alpha1_queue.yaml
  hack/.golint_failures
  hack/run-e2e.sh
  pkg/apis/extensions/v1alpha1/doc.go
  pkg/apis/extensions/v1alpha1/job.go
  pkg/apis/extensions/v1alpha1/register.go
  pkg/apis/extensions/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/scheduling/v1alpha1/register.go
  pkg/apis/scheduling/v1alpha1/types.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/extensions/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/extensions/v1alpha1/extensions_client.go
  pkg/client/clientset/versioned/typed/extensions/v1alpha1/fake/doc.go
  pkg/client/clientset/versioned/typed/extensions/v1alpha1/fake/fake_extensions_client.go
  pkg/client/clientset/versioned/typed/extensions/v1alpha1/fake/fake_job.go
  pkg/client/clientset/versioned/typed/extensions/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/extensions/v1alpha1/job.go
  pkg/client/informers/externalversions/extensions/interface.go
  pkg/client/informers/externalversions/extensions/v1alpha1/interface.go
  pkg/client/informers/externalversions/extensions/v1alpha1/job.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/extensions/v1alpha1/expansion_generated.go
  pkg/client/listers/extensions/v1alpha1/job.go
  pkg/controller/job/job_controller.go
  pkg/controller/job/utils.go
  pkg/controller/queue/queue_controller.go
  pkg/controller/queue/utils.go
  pkg/karcli/job/common.go
  pkg/karcli/job/list.go
  pkg/karcli/job/run.go
  pkg/karcli/job/util.go
  pkg/scheduler/actions/reclaim/reclaim.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/plugins/nodeaffinity/nodeaffinity.go
  test/e2e.go
  test/util.go
Labels: cncf-cla: yes, size/XXL

#343 Added PodFitsHostPorts in kube-batchd.
  hack/.golint_failures
  pkg/scheduler/factory.go
  pkg/scheduler/plugins/hostport/hostport.go
  pkg/scheduler/util.go
  test/e2e.go
  test/util.go
Labels: cncf-cla: yes, size/L

#345 Enabled Namespace as Queue.
  cmd/kube-batchd/app/options/options.go
  cmd/kube-batchd/app/server.go
  example/job.yaml
  pkg/scheduler/api/job_info.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/event_handlers.go
  pkg/scheduler/scheduler.go
Labels: cncf-cla: yes, size/L

#346 Renamed vars
  pkg/scheduler/api/job_info.go
Labels: cncf-cla: yes, size/L

#348 Updated tutorial.
  doc/usage/tutorial.md
Labels: cncf-cla: yes, size/M

#347 Updated deployment configurations.
  Makefile
  deployment/Dockerfile
  deployment/Dockerfile.ctrl
  deployment/Dockerfile.sched
  deployment/kube-arbitrator/Chart.yaml
  deployment/kube-arbitrator/templates/deployment.yaml
  deployment/kube-arbitrator/values.yaml
Labels: cncf-cla: yes, size/M

#349 Updated deployment configurations.
  deployment/kube-arbitrator/templates/deployment.yaml
  deployment/kube-arbitrator/templates/scheduling_v1alpha1_podgroup.yaml
  deployment/kube-arbitrator/templates/scheduling_v1alpha1_queue.yaml
  example/role.yaml
Labels: cncf-cla: yes, size/M

#350 Added overall architect.
  README.md
  doc/images/kube-batchd.png
Labels: cncf-cla: yes, size/XS

#352 Updated notes of helm chart.
  deployment/kube-arbitrator/templates/NOTES.txt
Labels: cncf-cla: yes

#353 fix deployment file invalid error
  deployment/kube-arbitrator/templates/deployment.yaml
Labels: cncf-cla: yes, size/XS

#355 Cherry Pick [Sep 7, 2018]
  README.md
  deployment/kube-arbitrator/templates/NOTES.txt
  deployment/kube-arbitrator/templates/deployment.yaml
  doc/images/kube-batchd.png
Labels: cncf-cla: yes, size/S

#354 Enabled Namespace as Queue by default.
  cmd/kube-batchd/app/options/options.go
Labels: cncf-cla: yes, size/XS

#357 Update docker hub's repo.
  Makefile
  deployment/kube-arbitrator/Chart.yaml
  deployment/kube-arbitrator/values.yaml
Labels: cncf-cla: yes, size/S

#358 Update image to kube-batchd.
  deployment/kube-arbitrator/templates/deployment.yaml
Labels: size/XS

#359 Update images.
  doc/usage/tutorial.md
Labels: cncf-cla: yes, size/XS

#362 fix typos in resource_info
  pkg/scheduler/api/resource_info.go
Labels: cncf-cla: yes, size/XS

#366 Improve the doc.
  doc/usage/tutorial.md
Labels: cncf-cla: yes, size/XS

#365 apply enabled namespace as Queue to PDB
  pkg/scheduler/api/job_info.go
Labels: cncf-cla: yes, size/S

#369 Automated cherry pick of #365 upstream release 0.2
  pkg/scheduler/api/job_info.go
Labels: size/S

#370 Added cherry pick tools.
  hack/cherry_pick_pull.sh
Labels: size/L

#363 fix e2e error reclaim
  cmd/kube-batchd/app/options/options.go
  hack/run-e2e.sh
  test/e2e.go
  test/util.go
Labels: cncf-cla: yes, size/L

#372 Enabled NamespaceAsQueue by default.
  cmd/kube-batchd/app/options/options.go
Labels: cncf-cla: yes, size/XS

#367 Tweak the doc.
  doc/usage/tutorial.md
Labels: cncf-cla: yes, size/XS

#373 Automated cherry pick of #363 upstream release 0.2
  cmd/kube-batchd/app/options/options.go
  hack/run-e2e.sh
  test/e2e.go
  test/util.go
Labels: cncf-cla: yes, size/L

#378 Updated github clone url.
  doc/usage/tutorial.md
Labels: cncf-cla: yes, size/XS

#379 Fixed ssn.Preemptable intersection issue.
  pkg/scheduler/framework/session.go
  pkg/scheduler/plugins/gang/gang.go
Labels: cncf-cla: yes, component/scheduler, sig/scheduling, size/M

#382 Fixed ssn.Preemptable intersection issue.
  pkg/scheduler/framework/session.go
  pkg/scheduler/plugins/gang/gang.go
Labels: cncf-cla: yes, size/M

#381 Added Toleration/Taint predicate.
  hack/.golint_failures
  hack/run-e2e.sh
  pkg/scheduler/factory.go
  pkg/scheduler/plugins/drf/drf.go
  pkg/scheduler/plugins/gang/gang.go
  pkg/scheduler/plugins/hostport/hostport.go
  pkg/scheduler/plugins/predicates/predicates.go
  pkg/scheduler/util.go
  test/e2e.go
  test/util.go
Labels: cncf-cla: yes, size/L
