Repository kubernetes-sigs/kube-batch, pull requests merged in 2018-08, with the labels that each got.

#320 Using annotation for PodGroup.
  pkg/apis/core/v1alpha1/labels.go
  pkg/controller/job/utils.go
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/cache/event_handlers.go
Labels: cncf-cla: yes, size/L

#321 Added PodGroup status.
  config/crds/core_v1alpha1_podgroup.yaml
  config/crds/extensions_v1alpha1_job.yaml
  pkg/apis/core/v1alpha1/types.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/extensions/v1alpha1/job.go
Labels: cncf-cla: yes, size/M

#322 Enhanced e2e test cmd.
  Makefile
  test/util.go
Labels: cncf-cla: yes, size/XS

#324 Enabled admission plugins.
  .travis.yml
  Makefile
  hack/dind-cluster-v1.11.sh
  hack/e2e-cluster.sh
  hack/run-e2e.sh
  pkg/scheduler/plugins/nodeaffinity/nodeaffinity.go
  test/util.go
Labels: cncf-cla: yes, size/L

#327 Fixed finding preemptee jobs issue.
  pkg/scheduler/actions/preempt/preempt.go
Labels: cncf-cla: yes, size/M

#330 Fixed potential division by zero.
  hack/.golint_failures
  pkg/scheduler/api/helpers/helpers.go
  pkg/scheduler/api/resource_info.go
  pkg/scheduler/plugins/drf/drf.go
  pkg/scheduler/plugins/proportion/proportion.go
Labels: cncf-cla: yes, size/M

#331 Do preemption within Queue.
  pkg/scheduler/actions/preempt/preempt.go
Labels: cncf-cla: yes, size/L

#332 Fixed API definition typo.
  pkg/apis/scheduling/v1alpha1/types.go
  pkg/apis/scheduling/v1alpha1/zz_generated.deepcopy.go
Labels: cncf-cla: yes, size/XS

#334 Added reclaim features.
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/actions/reclaim/reclaim.go
  pkg/scheduler/api/cluster_info.go
  pkg/scheduler/api/helpers/helpers.go
  pkg/scheduler/api/types.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/factory.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/plugins/proportion/proportion.go
  pkg/scheduler/util.go
  test/e2e.go
  test/util.go
Labels: cncf-cla: yes, size/XL

#336 Added powered list.
  doc/powered-by.md
Labels: size/XS

#338 Fixed reclaim for multiple tasks of queue.
  pkg/scheduler/framework/event.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/plugins/proportion/proportion.go
Labels: cncf-cla: yes, size/M

#339 Preempt multiple tasks.
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/actions/reclaim/reclaim.go
  pkg/scheduler/framework/event.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/plugins/drf/drf.go
  pkg/scheduler/plugins/gang/gang.go
  pkg/scheduler/plugins/proportion/proportion.go
Labels: cncf-cla: yes, size/L

#341 Add Tusimple
  doc/powered-by.md
Labels: cncf-cla: yes, size/XS
