Repository kubernetes-sigs/kube-batch, pull requests merged in 2018-05, with the labels that each got.

#208 docker images for kube-batchd
  Makefile
  deployment/Dockerfile
  deployment/kube-batchd.yaml
  doc/usage/batchd_tutorial.md
Labels: cncf-cla: yes, size/L

#209 Bug fix: error handling for createQueueCRD()
  pkg/batchd/controller/queue_controller.go
Labels: cncf-cla: yes, size/XS

#210 Bug fix: update PDB for QueueJob when its Replicas is changed
  pkg/batchd/controller/queuejob/controller.go
Labels: cncf-cla: yes, size/M

#211 Code cleanup.
  cmd/kube-batchd/app/server.go
  cmd/kube-batchd/main.go
  pkg/batchd/apis/v1/queuejob.go
  pkg/batchd/controller/policy/policy_controller.go
  pkg/batchd/controller/queue/queue_controller.go
  pkg/batchd/controller/queuejob/queuejob_controller.go
  pkg/batchd/policy/factory.go
  pkg/batchd/policy/plugins/drf/drf.go
  pkg/batchd/policy/plugins/drf/drf_test.go
  pkg/batchd/policy/plugins/drf/podset_info.go
  pkg/batchd/policy/plugins/drf/utils.go
Labels: cncf-cla: yes, size/M

#214 Fix golint errors.
  hack/.golint_failures
Labels: cncf-cla: yes, size/XS

#216 Fixed verify.
  hack/.golint_failures
Labels: size/XS

#217 Rename action interface.
  pkg/batchd/policy/actions/allocate/allocate.go
  pkg/batchd/policy/factory.go
  pkg/batchd/policy/interface.go
Labels: cncf-cla: yes, size/M

#224 Rename Allocate action and added Task Status.
  pkg/batchd/apis/types.go
  pkg/batchd/policy/actions/allocate/allocate.go
Labels: cncf-cla: yes, size/M

#225 Rename PodSet/Pod.
  pkg/batchd/cache/cache.go
  pkg/batchd/cache/cache_snapshot.go
  pkg/batchd/cache/cache_test.go
  pkg/batchd/cache/job_info.go
  pkg/batchd/cache/job_info_test.go
  pkg/batchd/cache/node_info.go
  pkg/batchd/cache/node_info_test.go
  pkg/batchd/cache/queue_info.go
  pkg/batchd/cache/queue_info_test.go
  pkg/batchd/controller/policy/policy_controller.go
  pkg/batchd/policy/actions/allocate/allocate.go
  pkg/batchd/policy/actions/allocate/allocate_test.go
  pkg/batchd/policy/actions/allocate/podset_info.go
Labels: cncf-cla: yes, size/L

#227 Add unit tests for GPU allocation
  pkg/batchd/policy/actions/allocate/allocate_test.go
Labels: cncf-cla: yes, size/M

#230 Rename PodSet to Job.
  pkg/batchd/cache/cache.go
  pkg/batchd/cache/cache_test.go
  pkg/batchd/cache/cluster_info.go
  pkg/batchd/cache/interface.go
  pkg/batchd/cache/queue_info.go
  pkg/batchd/cache/queue_info_test.go
  pkg/batchd/controller/policy/policy_controller.go
  pkg/batchd/policy/actions/allocate/allocate.go
  pkg/batchd/policy/actions/allocate/allocate_test.go
Labels: cncf-cla: yes, size/L

#231 Removed Policy arg.
  cmd/kube-batchd/app/options/options.go
  cmd/kube-batchd/app/server.go
  pkg/batchd/controller/policy/policy_controller.go
  pkg/batchd/policy/factory.go
Labels: cncf-cla: yes, size/S

#232 Removed tmp binaries.
  Makefile
Labels: size/XS
