Repository kubernetes-sigs/kube-batch, pull requests merged in 2019-05, with the labels that each got.

#839 Fixed the Pod failure event reason string for the k8s conformance tes…
  pkg/scheduler/cache/cache.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#841 Added Queue Capability.
  pkg/apis/scheduling/v1alpha1/types.go
  pkg/apis/scheduling/v1alpha1/zz_generated.deepcopy.go
  pkg/scheduler/util.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#843 Changing the event source to the right scheduler name
  cmd/kube-batch/app/server.go
  pkg/scheduler/cache/cache.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#844 Revert Vkctl queue subcommand
  cmd/cli/queue.go
  pkg/cli/queue/common.go
  pkg/cli/queue/create.go
  pkg/cli/queue/list.go
  pkg/cli/queue/util.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/L

#850 Updating running condition for pod group phase
  pkg/scheduler/framework/session.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#849 Add Comment in allocate
  pkg/scheduler/actions/allocate/allocate.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#848 Use KIND instead of DIND & Include Skipped test cases
  Makefile
  hack/e2e-kind-config.yaml
  hack/run-e2e-kind.sh
  test/e2e/job.go
  test/e2e/queue.go
  test/e2e/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#856 Add Wait time for KIND cluster to become ready
  hack/run-e2e-kind.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#854 Added Configuration to enable/disable predicates
  doc/usage/plugins/predicates.md
  pkg/scheduler/framework/arguments.go
  pkg/scheduler/plugins/predicates/predicates.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#855 support priorities map-reduce
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/framework/session_plugins.go
  pkg/scheduler/plugins/nodeorder/nodeorder.go
  pkg/scheduler/util/scheduler_helper.go
  pkg/scheduler/util/scheduler_helper_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#860 Fix wrong calculation for nodeinfo used
  pkg/scheduler/api/node_info.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#730 Fix wrong calculation for queue deserved in proportion plugin
  pkg/scheduler/api/resource_info.go
  pkg/scheduler/plugins/proportion/proportion.go
  test/e2e/job.go
  test/e2e/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#859 update node info no matter what node info changed
  pkg/scheduler/cache/event_handlers.go
Labels: approved, cncf-cla: yes, lgtm, size/S
