Repository kubernetes-sigs/kube-batch, pull requests merged in 2019-03, with the labels that each got.

#610 Updated log level.
  hack/run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, size/XS

#609 Added conformance plugin.
  hack/.golint_failures
  hack/run-e2e.sh
  pkg/scheduler/actions/reclaim/reclaim.go
  pkg/scheduler/plugins/conformance/conformance.go
  pkg/scheduler/plugins/prioritize/prioritize.go
  test/e2e/job.go
  test/e2e/predicates.go
  test/e2e/prioritize.go
  test/e2e/queue.go
  test/e2e/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#604 Moved default implementation from pkg.
  cmd/kube-batch/main.go
  pkg/scheduler/actions/factory.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/plugins/factory.go
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#615 Handled minAvailable task everytime.
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/plugins/gang/gang.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#603 Added PriorityClass to PodGroup.
  pkg/apis/scheduling/v1alpha1/types.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/event_handlers.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#617 Automated cherry pick of #615: Handled minAvailable task everytime.
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/plugins/gang/gang.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#616 Add Kubemark Benchmark Design Doc
  doc/design/Benchmark/kubemark/kubemark-benchmarking.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#619 Automated cherry pick of #603: Added PriorityClass to PodGroup.
  pkg/apis/scheduling/v1alpha1/types.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/event_handlers.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#618 Added JobPriority e2e.
  pkg/scheduler/api/job_info.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/event_handlers.go
  test/e2e/job.go
  test/e2e/predicates.go
  test/e2e/prioritize.go
  test/e2e/queue.go
  test/e2e/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#620 Automated cherry pick of #618: Added JobPriority e2e.
  pkg/scheduler/api/job_info.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/event_handlers.go
  test/e2e/job.go
  test/e2e/predicates.go
  test/e2e/prioritize.go
  test/e2e/queue.go
  test/e2e/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#622 Update doc & deployment.
  config/crds/scheduling_v1alpha1_podgroup.yaml
  deployment/kube-batch/templates/default.yaml
  deployment/kube-batch/templates/scheduling_v1alpha1_podgroup.yaml
  doc/usage/tutorial.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#623 Automated cherry pick of #622: Update doc & deployment.
  config/crds/scheduling_v1alpha1_podgroup.yaml
  deployment/kube-batch/templates/default.yaml
  deployment/kube-batch/templates/scheduling_v1alpha1_podgroup.yaml
  doc/usage/tutorial.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#625 Rename PrioritizeFn to NodeOrderFn
  config/kube-batch-conf.yaml
  example/kube-batch-conf.yaml
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/api/types.go
  pkg/scheduler/conf/scheduler_conf.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/framework/session_plugins.go
  pkg/scheduler/plugins/factory.go
  pkg/scheduler/plugins/nodeorder/nodeorder.go
  pkg/scheduler/util.go
  test/e2e/nodeorder.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#626 Fix helm deployment
  deployment/kube-batch/templates/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#627 cherry pick of #626: Fix helm deployment
  deployment/kube-batch/templates/deployment.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#628 Automated cherry pick of #625: Change Plugin name prioritize to nodeOrder
  config/kube-batch-conf.yaml
  example/kube-batch-conf.yaml
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/api/types.go
  pkg/scheduler/conf/scheduler_conf.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/framework/session_plugins.go
  pkg/scheduler/plugins/factory.go
  pkg/scheduler/plugins/nodeorder/nodeorder.go
  pkg/scheduler/util.go
  test/e2e/nodeorder.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#592 Add performance metrics for scheduling
  Gopkg.lock
  Gopkg.toml
  cmd/kube-batch/app/options/options.go
  cmd/kube-batch/app/server.go
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/framework/framework.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/metrics/metrics.go
  pkg/scheduler/plugins/gang/gang.go
  pkg/scheduler/scheduler.go
  vendor/github.com/prometheus/client_golang/prometheus/collector.go
  vendor/github.com/prometheus/client_golang/prometheus/counter.go
  vendor/github.com/prometheus/client_golang/prometheus/desc.go
  vendor/github.com/prometheus/client_golang/prometheus/doc.go
  vendor/github.com/prometheus/client_golang/prometheus/fnv.go
  vendor/github.com/prometheus/client_golang/prometheus/gauge.go
  vendor/github.com/prometheus/client_golang/prometheus/go_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/histogram.go
  vendor/github.com/prometheus/client_golang/prometheus/http.go
  vendor/github.com/prometheus/client_golang/prometheus/internal/metric.go
  vendor/github.com/prometheus/client_golang/prometheus/labels.go
  vendor/github.com/prometheus/client_golang/prometheus/metric.go
  vendor/github.com/prometheus/client_golang/prometheus/observer.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/promauto/auto.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_1_8.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_pre_1_8.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client_1_8.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/registry.go
  vendor/github.com/prometheus/client_golang/prometheus/summary.go
  vendor/github.com/prometheus/client_golang/prometheus/timer.go
  vendor/github.com/prometheus/client_golang/prometheus/untyped.go
  vendor/github.com/prometheus/client_golang/prometheus/value.go
  vendor/github.com/prometheus/client_golang/prometheus/vec.go
  vendor/github.com/prometheus/client_golang/prometheus/wrap.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#629 Automated cherry pick of #592: Update prometheus vendor libs
  Gopkg.lock
  Gopkg.toml
  cmd/kube-batch/app/options/options.go
  cmd/kube-batch/app/server.go
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/framework/framework.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/metrics/metrics.go
  pkg/scheduler/plugins/gang/gang.go
  pkg/scheduler/scheduler.go
  vendor/github.com/prometheus/client_golang/prometheus/collector.go
  vendor/github.com/prometheus/client_golang/prometheus/counter.go
  vendor/github.com/prometheus/client_golang/prometheus/desc.go
  vendor/github.com/prometheus/client_golang/prometheus/doc.go
  vendor/github.com/prometheus/client_golang/prometheus/fnv.go
  vendor/github.com/prometheus/client_golang/prometheus/gauge.go
  vendor/github.com/prometheus/client_golang/prometheus/go_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/histogram.go
  vendor/github.com/prometheus/client_golang/prometheus/http.go
  vendor/github.com/prometheus/client_golang/prometheus/internal/metric.go
  vendor/github.com/prometheus/client_golang/prometheus/labels.go
  vendor/github.com/prometheus/client_golang/prometheus/metric.go
  vendor/github.com/prometheus/client_golang/prometheus/observer.go
  vendor/github.com/prometheus/client_golang/prometheus/process_collector.go
  vendor/github.com/prometheus/client_golang/prometheus/promauto/auto.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_1_8.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/delegator_pre_1_8.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/http.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client_1_8.go
  vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
  vendor/github.com/prometheus/client_golang/prometheus/registry.go
  vendor/github.com/prometheus/client_golang/prometheus/summary.go
  vendor/github.com/prometheus/client_golang/prometheus/timer.go
  vendor/github.com/prometheus/client_golang/prometheus/untyped.go
  vendor/github.com/prometheus/client_golang/prometheus/value.go
  vendor/github.com/prometheus/client_golang/prometheus/vec.go
  vendor/github.com/prometheus/client_golang/prometheus/wrap.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#630 v0.4.1 Release Notes
  CHANGLOG.md
  Makefile
  deployment/kube-batch/Chart.yaml
  deployment/kube-batch/values.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#632 Set schedConf to defaultSchedulerConf if failing to readSchedulerConf
  pkg/scheduler/scheduler.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#631 Add helm hook crd-install to fix helm install error
  deployment/kube-batch/templates/scheduling_v1alpha1_podgroup.yaml
  deployment/kube-batch/templates/scheduling_v1alpha1_queue.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#633 Added new PRs.
  CHANGLOG.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#634 Automated cherry pick of #630: v0.4.1 Release Notes #631: Add helm hook crd-install to fix helm install error #632: Set schedConf to defaultSchedulerConf if failing to #633: Added new PRs.
  CHANGLOG.md
  Makefile
  deployment/kube-batch/Chart.yaml
  deployment/kube-batch/templates/scheduling_v1alpha1_podgroup.yaml
  deployment/kube-batch/templates/scheduling_v1alpha1_queue.yaml
  deployment/kube-batch/values.yaml
  pkg/scheduler/scheduler.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#636 add balanced resource priority
  pkg/scheduler/plugins/nodeorder/nodeorder.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#639 Support Plugin Arguments
  pkg/scheduler/conf/scheduler_conf.go
  pkg/scheduler/framework/framework.go
  pkg/scheduler/framework/plugins.go
  pkg/scheduler/plugins/conformance/conformance.go
  pkg/scheduler/plugins/drf/drf.go
  pkg/scheduler/plugins/gang/gang.go
  pkg/scheduler/plugins/nodeorder/nodeorder.go
  pkg/scheduler/plugins/predicates/predicates.go
  pkg/scheduler/plugins/priority/priority.go
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#644 Fix Typos
  pkg/scheduler/actions/reclaim/reclaim.go
  pkg/scheduler/api/helpers.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/cache/event_handlers.go
  pkg/scheduler/plugins/drf/drf.go
  pkg/scheduler/plugins/predicates/predicates.go
  pkg/scheduler/plugins/priority/priority.go
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#640 Support Weight for NodeOrder Plugin
  pkg/scheduler/plugins/nodeorder/nodeorder.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#643 Return err in Allocate if any error occurs
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/framework/session.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#642 Add event when task is scheduled
  pkg/scheduler/cache/cache.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#638 Take init containers into account when getting pod resource request
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/backfill/backfill.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/actions/reclaim/reclaim.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/api/pod_info.go
  pkg/scheduler/api/pod_info_test.go
  pkg/scheduler/api/resource_info.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#645 Order task, job, queue by CreationTimestamp first, then by UID
  pkg/scheduler/framework/session_plugins.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#647 In allocate, skip adding Job if its queue is not found
  pkg/scheduler/actions/allocate/allocate.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#651 Return err in functions of session.go if any error occurs
  pkg/scheduler/framework/session.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#652 Change run option SchedulePeriod's type to make it clear
  cmd/kube-batch/app/options/options.go
  cmd/kube-batch/app/options/options_test.go
  pkg/scheduler/scheduler.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#655 Do graceful eviction using default policy
  pkg/scheduler/cache/cache.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#656 Volunteer to help review
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#658 Address helm install error in tutorial.md
  doc/usage/tutorial.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#649 Preempt lowest priority task first
  pkg/scheduler/actions/preempt/preempt.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#660 Fix Resource Sub exception in Reclaim&Preempt Actions
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/actions/reclaim/reclaim.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#666 Fix wrong caculation for deserved in proportion plugin
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#671 Reduce image size
  Makefile
  deployment/images/Dockerfile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#673 Do not create PodGroup and Job for task whose scheduler is not kube-b…
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/cache_test.go
  pkg/scheduler/cache/event_handlers.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#674 Automated cherry pick of #636: add balanced resource priority
  pkg/scheduler/plugins/nodeorder/nodeorder.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#676 Automated cherry pick of #639: Support Plugin Arguments
  pkg/scheduler/conf/scheduler_conf.go
  pkg/scheduler/framework/framework.go
  pkg/scheduler/framework/plugins.go
  pkg/scheduler/plugins/conformance/conformance.go
  pkg/scheduler/plugins/drf/drf.go
  pkg/scheduler/plugins/gang/gang.go
  pkg/scheduler/plugins/nodeorder/nodeorder.go
  pkg/scheduler/plugins/predicates/predicates.go
  pkg/scheduler/plugins/priority/priority.go
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#677 Automated cherry pick of #644: Fix Typos
  pkg/scheduler/actions/reclaim/reclaim.go
  pkg/scheduler/api/helpers.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/cache/event_handlers.go
  pkg/scheduler/plugins/drf/drf.go
  pkg/scheduler/plugins/predicates/predicates.go
  pkg/scheduler/plugins/priority/priority.go
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#687 Automated cherry pick of #640: Support Weight for NodeOrder Plugin
  pkg/scheduler/plugins/nodeorder/nodeorder.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#685 Automated cherry pick of #643: Return err in Allocate if any error occurs #642: Add event when task is scheduled #638: Take init containers into account when getting pod resource #645: Order task by CreationTimestamp first, then by UID #647: In allocate, skip adding Job if its queue is not found #651: Return err in functions of session.go if any error occurs #652: Change run option SchedulePeriod's type to make it clear #655: Do graceful eviction using default policy #658: Address helm install error in tutorial.md #649: Preempt lowest priority task first #660: Fix sub exception in reclaim and preempt #666: Fix wrong caculation for deserved in proportion plugin #671: Change base image to alphine to reduce image size #673: Do not create PodGroup and Job for task whose scheduler is
  Makefile
  cmd/kube-batch/app/options/options.go
  cmd/kube-batch/app/options/options_test.go
  deployment/images/Dockerfile
  doc/usage/tutorial.md
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/backfill/backfill.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/actions/reclaim/reclaim.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/api/pod_info.go
  pkg/scheduler/api/pod_info_test.go
  pkg/scheduler/api/resource_info.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/cache_test.go
  pkg/scheduler/cache/event_handlers.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/framework/session_plugins.go
  pkg/scheduler/plugins/proportion/proportion.go
  pkg/scheduler/scheduler.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#689 Add Release Notes for v0.4.2
  CHANGLOG.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#690 Automated cherry pick of #689: Update CHANGLOG.md
  CHANGLOG.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#691 Update the version to v0.4.2
  Makefile
  deployment/kube-batch/values.yaml
  doc/usage/tutorial.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#692 Automated cherry pick of #691: Update the version to v0.4.2
  Makefile
  deployment/kube-batch/values.yaml
  doc/usage/tutorial.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
