Repository kubernetes-sigs/kube-batch, pull requests merged in 2019-02, with the labels that each got.

#582 Add Node Priority Design Doc
  doc/design/node-priority.md
  doc/images/Node-Priority.png
Labels: approved, cncf-cla: yes, lgtm, size/S

#583 Fixed e2e typo.
  pkg/scheduler/cache/cache.go
  test/e2e/queue.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#584 Replaced FIFO by workqueue.
  pkg/scheduler/cache/cache.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#585 Removed invalid error log.
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/interface.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#586 Automated cherry pick of #584: Replaced FIFO by workqueue. #585: Removed invalid error log.
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/interface.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#594 Fixed Job.Clone issue.
  pkg/scheduler/api/job_info.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#595 Automated cherry pick of #594: Fixed Job.Clone issue.
  pkg/scheduler/api/job_info.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#599 Fixed import order.
  pkg/scheduler/scheduler.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#600 Fixed duplicated queue in preempt action.
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/actions/reclaim/reclaim.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#596 Set default PodGroup for Pods.
  pkg/scheduler/api/job_info.go
  pkg/scheduler/api/job_info_test.go
  pkg/scheduler/api/types.go
  pkg/scheduler/api/util.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/cache_test.go
  pkg/scheduler/cache/event_handlers.go
  test/e2e/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#602 Automated cherry pick of #596: Set default PodGroup for Pods.
  pkg/scheduler/api/job_info.go
  pkg/scheduler/api/job_info_test.go
  pkg/scheduler/api/types.go
  pkg/scheduler/api/util.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/cache_test.go
  pkg/scheduler/cache/event_handlers.go
  test/e2e/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#601 Automated cherry pick of #600: Fixed duplicated queue in preempt/reclaim action.
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/actions/reclaim/reclaim.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#587 Adding node priority
  Gopkg.lock
  example/kube-batch-conf.yaml
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/api/types.go
  pkg/scheduler/conf/scheduler_conf.go
  pkg/scheduler/factory.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/framework/session_plugins.go
  pkg/scheduler/plugins/prioritize/prioritize.go
  pkg/scheduler/util.go
  pkg/scheduler/util/sort.go
  test/e2e/prioritize.go
  test/e2e/util.go
  vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/BUILD
  vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/balanced_resource_allocation.go
  vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/image_locality.go
  vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/interpod_affinity.go
  vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/least_requested.go
  vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/metadata.go
  vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/most_requested.go
  vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/node_affinity.go
  vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/node_label.go
  vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/node_prefer_avoid_pods.go
  vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/reduce.go
  vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/requested_to_capacity_ratio.go
  vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/resource_allocation.go
  vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/resource_limits.go
  vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/selector_spreading.go
  vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/taint_toleration.go
  vendor/k8s.io/kubernetes/pkg/scheduler/algorithm/priorities/test_util.go
  vendor/k8s.io/kubernetes/pkg/util/node/BUILD
  vendor/k8s.io/kubernetes/pkg/util/node/node.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#607 Fixed flaky test.
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/actions/reclaim/reclaim.go
  pkg/scheduler/api/cluster_info.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/framework/statement.go
  pkg/scheduler/plugins/gang/gang.go
  pkg/scheduler/plugins/predicates/predicates.go
  pkg/scheduler/plugins/prioritize/prioritize.go
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, cncf-cla: yes, lgtm, size/L
