Repository kubernetes-sigs/kube-batch, pull requests merged in 2019-11, with the labels that each got.

#906 derive shadow pod group priority from pod priority
  pkg/scheduler/cache/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#908 shadow pod group derives min member from pod annotations
  pkg/apis/scheduling/v1alpha1/labels.go
  pkg/apis/scheduling/v1alpha2/labels.go
  pkg/scheduler/cache/cache_test.go
  pkg/scheduler/cache/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#910 correct the mismatched weights & fix typo
  pkg/scheduler/plugins/nodeorder/nodeorder.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/S

#909 revert cache to original state on evict and bind errors
  pkg/scheduler/api/job_info.go
  pkg/scheduler/api/node_info.go
  pkg/scheduler/api/node_info_test.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/cache_test.go
  pkg/scheduler/cache/event_handlers.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/framework/statement.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#913 fix Resource Less/LessEqual
  pkg/scheduler/api/resource_info.go
  pkg/scheduler/api/resource_info_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#912 Change Statement unevict method to call UpdateTask
  pkg/scheduler/framework/statement.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#916 fix validate victims check
  pkg/scheduler/actions/preempt/preempt.go
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS

#915 Fix wrong condition for reclaim action
  pkg/scheduler/actions/reclaim/reclaim.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#917 add support for most requested priority
  pkg/scheduler/plugins/nodeorder/nodeorder.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M
