Repository kubernetes-sigs/kube-batch, pull requests merged in 2019-01, with the labels that each got.

#527 Automated cherry pick of #517: Updated version to 0.3
  deployment/kube-batch/values.yaml
  doc/usage/tutorial.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#534 Removed old design doc to avoid confusion.
  doc/design/preemption.md
  doc/design/queue_api.md
  doc/design/queuejob_api.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#533 Added PodGroup Phase in Status.
  doc/design/podgroup-status.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#540 Examine all pending tasks in a job
  pkg/scheduler/actions/allocate/allocate.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#541 Automated cherry pick of #540: Examine all pending tasks in one loop
  pkg/scheduler/actions/allocate/allocate.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#544 Dynamic Plugin Configuration
  doc/design/plugin-conf.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#525 Added Phase and Conditions to PodGroup.Status struct
  pkg/apis/scheduling/v1alpha1/types.go
  pkg/apis/scheduling/v1alpha1/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#547 Fixed status protobuf id.
  pkg/apis/scheduling/v1alpha1/types.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#549 Added name when register plugin.
  pkg/scheduler/framework/interface.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/plugins/drf/drf.go
  pkg/scheduler/plugins/gang/gang.go
  pkg/scheduler/plugins/predicates/predicates.go
  pkg/scheduler/plugins/priority/priority.go
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#550 Added SchedulerConfiguration type.
  pkg/scheduler/conf/schedConf.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#552 Multi tiers for plugins.
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/framework/framework.go
  pkg/scheduler/framework/interface.go
  pkg/scheduler/framework/plugins.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/framework/session_plugins.go
  pkg/scheduler/plugins/drf/drf.go
  pkg/scheduler/plugins/gang/gang.go
  pkg/scheduler/plugins/predicates/predicates.go
  pkg/scheduler/plugins/priority/priority.go
  pkg/scheduler/plugins/proportion/proportion.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#553 Renamed fn name.
  pkg/scheduler/api/types.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/framework/session_plugins.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#548 Add e2e test for different task resource requests
  test/e2e/job.go
  test/e2e/util.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#554 Updated plugin conf design according to implementation.
  cmd/kube-batch/app/options/options.go
  doc/design/plugin-conf.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#556 Added VolumeScheduling.
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/cache_test.go
  pkg/scheduler/cache/interface.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/plugins/gang/gang.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#558 Reduce verbosity level for recurring logs
  contrib/DLaaS/pkg/scheduler/plugins/priority/priority.go
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/actions/reclaim/reclaim.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/plugins/gang/gang.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#559 Automated cherry pick of #558: Reduce verbosity level for recurring logs
  contrib/DLaaS/pkg/scheduler/plugins/priority/priority.go
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/actions/reclaim/reclaim.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/plugins/gang/gang.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#560 Update PodGroup status.
  pkg/apis/scheduling/v1alpha1/types.go
  pkg/apis/scheduling/v1alpha1/zz_generated.deepcopy.go
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/api/helpers.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/api/types.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/cache_test.go
  pkg/scheduler/cache/event_handlers.go
  pkg/scheduler/cache/interface.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/framework/session_plugins.go
  pkg/scheduler/plugins/gang/gang.go
  test/e2e/job.go
  test/e2e/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#562 Update PodGroup status.
  doc/design/podgroup-status.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#563 Automated cherry pick of #562: Update PodGroup status. #560: Update PodGroup status.
  doc/design/podgroup-status.md
  pkg/apis/scheduling/v1alpha1/types.go
  pkg/apis/scheduling/v1alpha1/zz_generated.deepcopy.go
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/api/helpers.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/api/types.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/cache_test.go
  pkg/scheduler/cache/event_handlers.go
  pkg/scheduler/cache/interface.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/framework/session_plugins.go
  pkg/scheduler/plugins/gang/gang.go
  test/e2e/job.go
  test/e2e/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#565 Removed reclaim&preempt by default.
  example/kube-batch-conf.yaml
  hack/run-e2e.sh
  pkg/scheduler/conf/scheduler_conf.go
  pkg/scheduler/util.go
  test/e2e/util.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#570 Reverted PDB support.
  pkg/scheduler/api/helpers.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/event_handlers.go
  pkg/scheduler/cache/interface.go
  pkg/scheduler/framework/session.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#571 Automated cherry pick of #570: Reverted PDB support.
  pkg/scheduler/api/helpers.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/event_handlers.go
  pkg/scheduler/cache/interface.go
  pkg/scheduler/framework/session.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#569 v0.4 Release.
  CHANGLOG.md
  Makefile
  deployment/kube-batch/Chart.yaml
  deployment/kube-batch/values.yaml
  doc/usage/tutorial.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#573 Automated cherry pick of #569: v0.4 Release.
  CHANGLOG.md
  Makefile
  deployment/kube-batch/Chart.yaml
  deployment/kube-batch/values.yaml
  doc/usage/tutorial.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#574 Added apiextensions version.
  Gopkg.lock
  Gopkg.toml
Labels: approved, cncf-cla: yes, lgtm

#575 Updated 0.4 release note.
  CHANGLOG.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#577 Automated cherry pick of #575: Updated 0.4 release note.
  CHANGLOG.md
Labels: approved, cncf-cla: yes, lgtm

#578 Added more info of repo.
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#546 Delay Pod Creation.
  doc/design/delay-pod-creation.md
Labels: approved, cncf-cla: yes, component/controllers, lgtm, priority/important-soon, sig/scheduling, size/L

#579 Add metrics support documentation
  doc/design/metrics.md
Labels: approved, cncf-cla: yes, lgtm, size/M
