Repository kubernetes-sigs/kube-batch, pull requests merged in 2019-06, with the labels that each got.

#862 Migrate from dep to go modules to manage dependencies.
  CONTRIBUTING.md
  Gopkg.lock
  Gopkg.toml
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XXL

#863 [Cherry-Pick #26] Ignore nodes if out of syc.
  pkg/scheduler/api/node_info.go
  pkg/scheduler/api/node_info_test.go
  pkg/scheduler/api/types.go
  pkg/scheduler/cache/cache.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#865 update tutorial.md
  doc/usage/tutorial.md
Labels: approved, cncf-cla: yes, lgtm, needs-ok-to-test, size/XS
