Repository kubernetes-sigs/kube-batch, pull requests merged in 2019-04, with the labels that each got.

#693 Update helm chart version to 0.4.2
  deployment/kube-batch/Chart.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#696 Improve allocate performance by making predicate and priority concurr…
  pkg/scheduler/actions/allocate/allocate.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#700 Fix race condition for concurrent predicate and priority in allocate
  pkg/scheduler/actions/allocate/allocate.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#698 Add support for setting default value to the configuration
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/conf/scheduler_conf.go
  pkg/scheduler/framework/session_plugins.go
  pkg/scheduler/plugins/defaults.go
  pkg/scheduler/util.go
  pkg/scheduler/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#701 Apply for approver
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#668 Improve kube-batch documentation
  cmd/kube-batch/app/options/options.go
  doc/usage/tutorial.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#702 Fixed table issue in tutorial.
  doc/usage/tutorial.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#705 Add type Argument with some common parse function
  pkg/scheduler/framework/arguments.go
  pkg/scheduler/framework/arguments_test.go
  pkg/scheduler/framework/plugins.go
  pkg/scheduler/plugins/conformance/conformance.go
  pkg/scheduler/plugins/drf/drf.go
  pkg/scheduler/plugins/gang/gang.go
  pkg/scheduler/plugins/nodeorder/nodeorder.go
  pkg/scheduler/plugins/predicates/predicates.go
  pkg/scheduler/plugins/priority/priority.go
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#709 Fixed word issue in plugin-conf document.
  doc/design/plugin-conf.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#713 removing unnecessary entries and syntax changes
  doc/design/plugin-conf.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#711 distinguishing the key words in batch scheduler
  doc/design/node-priority.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#712 fixing grammatical errors
  doc/design/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#716 Improve preempt performance by predicate and priority concurrently
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/util/scheduler_helper.go
  pkg/scheduler/util/sort.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#717 Added resource predicates.
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/util/scheduler_helper.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#719 NodeOrderFn return float value
  pkg/scheduler/api/types.go
  pkg/scheduler/framework/session_plugins.go
  pkg/scheduler/plugins/nodeorder/nodeorder.go
  pkg/scheduler/util/scheduler_helper.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#721 Select only one best node for allocate
  pkg/scheduler/actions/allocate/allocate.go
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/util/scheduler_helper.go
  pkg/scheduler/util/scheduler_helper_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#714 [DOCS] Add the Execution Workflow for Allocation of Jobs to Nodes
  doc/design/dev/execution-flow.md
  doc/images/AllocateDesign.png
Labels: approved, cncf-cla: yes, lgtm, size/M

#650 Do not count in pipelined task when calculating ready tasks number
  pkg/scheduler/actions/preempt/preempt.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/conf/scheduler_conf.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/framework/session_plugins.go
  pkg/scheduler/plugins/defaults.go
  pkg/scheduler/plugins/gang/gang.go
  pkg/scheduler/util_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#723 [DOCS] Docs for Preempt action
  doc/design/preempt-action.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#725 add options to enable the feature of PriorityClass
  cmd/kube-batch/app/options/options.go
  cmd/kube-batch/app/options/options_test.go
  cmd/kube-batch/main.go
  pkg/scheduler/cache/cache.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#727 [DOCS] Docs for Reclaim Action
  doc/design/reclaim-action.md
Labels: approved, cncf-cla: yes, lgtm, size/M

#731 [Support Job Resource] Add job admission
  Gopkg.lock
  cmd/admission/app/options/options.go
  cmd/admission/app/server.go
  cmd/admission/main.go
  hack/.golint_failures
  pkg/admission/admission_controller.go
  pkg/admission/admit_job.go
  pkg/admission/mutate_job.go
  vendor/k8s.io/api/admission/v1beta1/doc.go
  vendor/k8s.io/api/admission/v1beta1/generated.pb.go
  vendor/k8s.io/api/admission/v1beta1/generated.proto
  vendor/k8s.io/api/admission/v1beta1/register.go
  vendor/k8s.io/api/admission/v1beta1/types.go
  vendor/k8s.io/api/admission/v1beta1/types_swagger_doc_generated.go
  vendor/k8s.io/api/admission/v1beta1/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#737 fix verify
  cmd/cli/job.go
  cmd/cli/vkctl.go
  cmd/controllers/app/options/options.go
  cmd/controllers/app/server.go
  cmd/controllers/main.go
  hack/.golint_failures
  pkg/apis/helpers/helpers.go
  pkg/cli/job/common.go
  pkg/cli/job/list.go
  pkg/cli/job/resume.go
  pkg/cli/job/run.go
  pkg/cli/job/suspend.go
  pkg/cli/job/util.go
  pkg/controllers/apis/job_info.go
  pkg/controllers/cache/cache.go
  pkg/controllers/cache/interface.go
  pkg/controllers/job/helpers/helpers.go
  pkg/controllers/job/job_controller.go
  pkg/controllers/job/job_controller_actions.go
  pkg/controllers/job/job_controller_handler.go
  pkg/controllers/job/job_controller_plugins.go
  pkg/controllers/job/job_controller_util.go
  pkg/controllers/job/plugins/env/env.go
  pkg/controllers/job/plugins/env/types.go
  pkg/controllers/job/plugins/factory.go
  pkg/controllers/job/plugins/interface/interface.go
  pkg/controllers/job/plugins/ssh/ssh.go
  pkg/controllers/job/plugins/ssh/types.go
  pkg/controllers/job/state/aborted.go
  pkg/controllers/job/state/aborting.go
  pkg/controllers/job/state/completing.go
  pkg/controllers/job/state/factory.go
  pkg/controllers/job/state/finished.go
  pkg/controllers/job/state/pending.go
  pkg/controllers/job/state/restarting.go
  pkg/controllers/job/state/running.go
  pkg/controllers/job/state/terminating.go
  pkg/controllers/job/state/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#734 Built binaries.
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/S

#738 Fix Golint Errors for pkg/admission and pkg/cli/job package
  hack/.golint_failures
  pkg/admission/admission_controller.go
  pkg/admission/admit_job.go
  pkg/admission/mutate_job.go
  pkg/cli/job/list.go
  pkg/cli/job/resume.go
  pkg/cli/job/run.go
  pkg/cli/job/suspend.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#740 Fix GoLint Errors in pkg/controllers/apis and pkg/controllers/cache packages
  hack/.golint_failures
  pkg/controllers/apis/job_info.go
  pkg/controllers/cache/cache.go
  pkg/controllers/cache/interface.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#739 Fix Golint Errors in cmd package
  cmd/admission/app/options/options.go
  cmd/admission/app/server.go
  cmd/controllers/app/options/options.go
  cmd/controllers/app/server.go
  cmd/kube-batch/app/options/options.go
  cmd/kube-batch/app/server.go
  hack/.golint_failures
Labels: approved, cncf-cla: yes, lgtm, size/S

#741 [Support Job Resource] Add volcano e2e
  hack/.golint_failures
  test/e2e/volcano/admission.go
  test/e2e/volcano/cli_util.go
  test/e2e/volcano/command.go
  test/e2e/volcano/e2e_test.go
  test/e2e/volcano/job_error_handling.go
  test/e2e/volcano/job_plugins.go
  test/e2e/volcano/job_scheduling.go
  test/e2e/volcano/mpi.go
  test/e2e/volcano/predicates.go
  test/e2e/volcano/queue.go
  test/e2e/volcano/util.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#742 Fix Golint Errors in pkg/controllers/job package
  hack/.golint_failures
  pkg/controllers/job/helpers/helpers.go
  pkg/controllers/job/job_controller_actions.go
  pkg/controllers/job/job_controller_plugins.go
  pkg/controllers/job/job_controller_util.go
  pkg/controllers/job/plugins/env/env.go
  pkg/controllers/job/plugins/env/types.go
  pkg/controllers/job/plugins/factory.go
  pkg/controllers/job/plugins/ssh/ssh.go
  pkg/controllers/job/plugins/ssh/types.go
  pkg/controllers/job/state/factory.go
  pkg/controllers/job/state/util.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#743 [Support Job Resource] Add related helm chart
  deployment/images/admission/Dockerfile
  deployment/images/controllers/Dockerfile
  deployment/volcano/Chart.yaml
  deployment/volcano/config/kube-batch.conf
  deployment/volcano/plugins/gen-admission-secret/gen-admission-secret.sh
  deployment/volcano/plugins/gen-admission-secret/plugin.yaml
  deployment/volcano/templates/admission-config.yaml
  deployment/volcano/templates/admission.yaml
  deployment/volcano/templates/batch_v1alpha1_job.yaml
  deployment/volcano/templates/bus_v1alpha1_command.yaml
  deployment/volcano/templates/controllers.yaml
  deployment/volcano/templates/default-queue.yaml
  deployment/volcano/templates/scheduler.yaml
  deployment/volcano/templates/scheduling_v1alpha1_podgroup.yaml
  deployment/volcano/templates/scheduling_v1alpha1_queue.yaml
  deployment/volcano/values.yaml
  example/volcano/duplicatedPolicyEvent-webhook-deny.yaml
  example/volcano/duplicatedTaskName-webhook-deny.yaml
  example/volcano/integrations/mpi/Dockerfile
  example/volcano/integrations/mpi/mpi-example.yaml
  example/volcano/job.yaml
  example/volcano/kube-batch-conf.yaml
  example/volcano/minAvailable-webhook-deny.yaml
  example/volcano/role.yaml
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#744 FixGolint in scheduler package
  hack/.golint_failures
  pkg/scheduler/cache/cache.go
  pkg/scheduler/cache/event_handlers.go
  pkg/scheduler/cache/interface.go
  pkg/scheduler/framework/arguments.go
  pkg/scheduler/framework/event.go
  pkg/scheduler/framework/framework.go
  pkg/scheduler/framework/interface.go
  pkg/scheduler/framework/plugins.go
  pkg/scheduler/framework/session.go
  pkg/scheduler/framework/session_plugins.go
  pkg/scheduler/framework/statement.go
  pkg/scheduler/plugins/conformance/conformance.go
  pkg/scheduler/plugins/drf/drf.go
  pkg/scheduler/plugins/gang/gang.go
  pkg/scheduler/plugins/predicates/predicates.go
  pkg/scheduler/plugins/priority/priority.go
  pkg/scheduler/plugins/proportion/proportion.go
  pkg/scheduler/scheduler.go
  pkg/scheduler/util/priority_queue.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#745 Fix Lint errors for pkg/scheduler/api package
  hack/.golint_failures
  pkg/scheduler/api/helpers.go
  pkg/scheduler/api/helpers/helpers.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/api/job_info_test.go
  pkg/scheduler/api/node_info.go
  pkg/scheduler/api/node_info_test.go
  pkg/scheduler/api/pod_info.go
  pkg/scheduler/api/queue_info.go
  pkg/scheduler/api/resource_info.go
  pkg/scheduler/api/types.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#746 [Support Job Resource] Add related document
  doc/design/job-api.md
  doc/images/volcano-intro.png
Labels: approved, cncf-cla: yes, lgtm, size/XL

#752 [Add Job Resource] Fix panic error when running job e2e tests
  pkg/controllers/apis/job_info.go
  pkg/controllers/cache/cache.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#750 [Add Job Resource] Support build&e2e tests workflow
  Makefile
  deployment/volcano/plugins/gen-admission-secret/gen-admission-secret.sh
  deployment/volcano/values.yaml
  hack/e2e-kind-config.yaml
  hack/run-e2e-kind.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#754 Removed inactive owners.
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#703 Docs for DRF Plugin
  doc/design/plugin/drf.md
  doc/design/plugin/drfjobordering.png
  doc/design/plugin/gangwithdrf.png
Labels: approved, cncf-cla: yes, lgtm, size/M

#706 Docs for task-order within Job
  doc/design/task-order.md
  doc/images/task_order.png
Labels: approved, cncf-cla: yes, lgtm, size/S

#715 [DOCS] Add workflow of Reclaim action
  doc/design/dev/reclaim-design.md
  doc/images/ReclaimDesign.png
Labels: approved, cncf-cla: yes, lgtm, size/M

#756 [Add Job Resource] Fix some issues when enabling e2e tests
  pkg/admission/admit_job.go
  pkg/controllers/job/job_controller.go
  pkg/controllers/job/job_controller_actions.go
  pkg/controllers/job/job_controller_handler.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#753 Enabled e2e-kind.
  .travis.yml
  hack/run-e2e-kind.sh
Labels: approved, cncf-cla: yes, lgtm, size/M

#758 Updated README accordingly.
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#759 Add document for e2e tests
  README.md
  hack/run-e2e-kind.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#767 Added volcano logo.
  README.md
  doc/images/volcano-logo.png
Labels: approved, cncf-cla: yes, lgtm, size/XS

#771 Add hzxuzhonghu to approver & reviewers
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#775 Implement error code handling in lifecyclePolicy
  Gopkg.lock
  Gopkg.toml
  pkg/admission/admission_controller.go
  pkg/admission/admit_job.go
  pkg/controllers/apis/job_info.go
  pkg/controllers/job/job_controller_handler.go
  pkg/controllers/job/job_controller_util.go
  test/e2e/admission.go
  test/e2e/job_error_handling.go
  vendor/github.com/hashicorp/errwrap/LICENSE
  vendor/github.com/hashicorp/errwrap/README.md
  vendor/github.com/hashicorp/errwrap/errwrap.go
  vendor/github.com/hashicorp/errwrap/go.mod
  vendor/github.com/hashicorp/go-multierror/.travis.yml
  vendor/github.com/hashicorp/go-multierror/LICENSE
  vendor/github.com/hashicorp/go-multierror/Makefile
  vendor/github.com/hashicorp/go-multierror/README.md
  vendor/github.com/hashicorp/go-multierror/append.go
  vendor/github.com/hashicorp/go-multierror/flatten.go
  vendor/github.com/hashicorp/go-multierror/format.go
  vendor/github.com/hashicorp/go-multierror/go.mod
  vendor/github.com/hashicorp/go-multierror/go.sum
  vendor/github.com/hashicorp/go-multierror/multierror.go
  vendor/github.com/hashicorp/go-multierror/prefix.go
  vendor/github.com/hashicorp/go-multierror/sort.go
Labels: approved, cncf-cla: yes, lgtm, size/XXL

#777 fix delete po err msg
  pkg/controllers/job/job_controller_handler.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#782 Fix typo
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#783 Keep kube-batch doc compatible
  README.md
  doc/usage/volcano_intro.md
Labels: approved, cncf-cla: yes, lgtm, size/L

#773 Abstract a common pod delete func
  pkg/controllers/job/job_controller.go
  pkg/controllers/job/job_controller_actions.go
  pkg/controllers/job/job_controller_plugins.go
  pkg/controllers/job/job_controller_util.go
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/L

#779 Help message for vkctl job
  cmd/cli/job.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#785 Fix Typo
  doc/usage/volcano_intro.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#787 Fix Broken image link
  doc/usage/volcano_intro.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#751 Add UT cases for Preempt Action
  pkg/scheduler/actions/allocate/allocate_test.go
  pkg/scheduler/actions/preempt/preempt_test.go
  pkg/scheduler/util/test_utils.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#796 Add Volcano Installation Tutorial Link
  doc/usage/volcano_intro.md
  example/volcano/integrations/mpi/Readme.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#795 support extended resource for kube-batch
  pkg/scheduler/api/helpers/helpers.go
  pkg/scheduler/api/job_info.go
  pkg/scheduler/api/resource_info.go
  pkg/scheduler/api/resource_info_test.go
  pkg/scheduler/plugins/drf/drf.go
  pkg/scheduler/plugins/proportion/proportion.go
Labels: approved, cncf-cla: yes, lgtm, size/XL

#792 Fix verify
  Makefile
Labels: approved, cncf-cla: yes, lgtm, size/XS

#793 Add document for MPI example
  example/volcano/integrations/mpi/mpi-example.yaml
Labels: approved, cncf-cla: yes, lgtm, size/M

#800 Add CheckNodeDiskPressure,CheckNodePIDPressure,CheckNodeMemoryPressur…
  pkg/scheduler/plugins/predicates/predicates.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#801 Add UT Cases for Reclaim Action
  pkg/scheduler/actions/reclaim/reclaim_test.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#808 Update tutorial.md
  doc/usage/tutorial.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#809 Prevent memory leak
  pkg/scheduler/cache/cache.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#807 Automated cherry pick of #725: add options to enable the feature of PriorityClass
  cmd/kube-batch/app/options/options.go
  cmd/kube-batch/app/options/options_test.go
  cmd/kube-batch/main.go
  pkg/scheduler/cache/cache.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#816 Migrate duplicated code in nodeorder and predicate plugin
  pkg/scheduler/plugins/nodeorder/nodeorder.go
  pkg/scheduler/plugins/predicates/predicates.go
  pkg/scheduler/plugins/util/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#811 Automated cherry pick of #809: Prevent memory leak
  pkg/scheduler/cache/cache.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#812 Added Queue status.
  config/crds/scheduling_v1alpha1_podgroup.yaml
  config/crds/scheduling_v1alpha1_queue.yaml
  pkg/apis/scheduling/v1alpha1/types.go
  pkg/apis/scheduling/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/scheduling/v1alpha1/fake/fake_queue.go
  pkg/client/clientset/versioned/typed/scheduling/v1alpha1/queue.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#819 Add script for e2e prow job
  hack/prow/prepare-and-run-e2e.sh
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/M

#817 Fix kubemark issue & Add document for kubemark test
  Makefile
  test/e2e/kube-batch/util.go
  test/kubemark/README.md
  test/kubemark/kube-batch.yaml
  test/kubemark/start-kubemark.sh
  test/kubemark/stop-kubemark.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#820 Adding subcommand queue create and list to vkctl
  cmd/cli/queue.go
  cmd/cli/vkctl.go
  pkg/cli/queue/common.go
  pkg/cli/queue/create.go
  pkg/cli/queue/list.go
  pkg/cli/queue/util.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#833 Add Vivo to who-is-using doc
  doc/usage/who-is-using.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#834 Added user list in README.
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S
