Repository kubernetes-sigs/kube-batch, pull requests merged in 2020-01, with the labels that each got.

#926 Run make generate-code to make ./hack/verify-gencode happy
  pkg/apis/scheduling/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/scheduling/v1alpha2/zz_generated.deepcopy.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#928 github.com/golang/lint now imports golang.org/x/lint
  go.mod
  go.sum
  hack/verify-golint.sh
Labels: approved, cncf-cla: yes, lgtm, size/S

#925 fix(helps):rm pkg/apis/helpers/helpers.go
  hack/.golint_failures
  pkg/apis/helpers/helpers.go
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/L

#927 Update README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, ok-to-test, size/XS

#924 Document framework, plugins and actions
  doc/design/framework.md
Labels: approved, cncf-cla: yes, lgtm, size/L
