Repository kubernetes-sigs/kube-batch, pull requests merged in 2022-07, with the labels that each got.

#962 Update Owners
  OWNERS
Labels: approved, cncf-cla: yes, size/XS

#970 Fix verify task
  .travis.yml
  go.mod
  go.sum
  pkg/apis/scheduling/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/scheduling/v1alpha2/zz_generated.deepcopy.go
  vendor.go
Labels: approved, cncf-cla: yes, lgtm, size/M, ok-to-test

#971 Update README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
